/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraficas;

import Excel.LeerExcel;
import Excel.LeerIva;
import Excel.pdfsJavaGenerador;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mauro
 */
public class AbmIva extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmIva
     */
    public AbmIva() {
        initComponents();
        this.jFileChooser1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Libro IVA");

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Users\\mauro\\Documents\\NetBeansProjects\\PocoPrecio"));
        jFileChooser1.setDialogTitle("Seleccion de Origen de Datos");
        jFileChooser1.setOpaque(true);

        jButton3.setText("Procesar Archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        File fichero;
        int resultado;
        this.jFileChooser1.setVisible(true);

        //FileNameExtensionFilter filtro = new FileNameExtensionFilter("txt","pdf");
        //this.jFileChooser1.setFileFilter(filtro);
        resultado=this.jFileChooser1.showOpenDialog(this);
        String seleccionado = null;
        if (JFileChooser.APPROVE_OPTION == resultado){

            fichero = this.jFileChooser1.getSelectedFile();
            seleccionado=fichero.getPath();
            
            
        }
        System.out.println(seleccionado);
        
        LeerExcel leer=new LeerExcel();
        try {
            leer.leerExcel1(seleccionado);
            this.dispose();
            
            /*
            String period=null;
            if(JOptionPane.showConfirmDialog(this,"Procesa el archivo seleccionado?","Aplicar Origen",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==1){
            }else{
            LeerIva iva=new LeerIva();
            period=JOptionPane.showInputDialog(this,"Ingrese periodo");
            iva.leerArchivo(seleccionado,period);
            }
            */
            /*
            LeerExcel leer=new LeerExcel();
            try {
            leer.leerExcel1("SubIva/iva ventas marzo2.xls");
            } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            */
            
            /*
            if(JOptionPane.showConfirmDialog(this,"Genera el pdf del periodo Procesado?","Generar PDF",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==1){
            }else{
            
            if(period!=null){
                
            }else{
            period=JOptionPane.showInputDialog(this,"Ingrese periodo");
            }
            pdfsJavaGenerador pd=new pdfsJavaGenerador();
            pd.setPeriodo(period);
            pd.run();
               
            }
            this.jFileChooser1.setVisible(false);
            
            */
        } catch (SQLException ex) {
            Logger.getLogger(AbmIva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
