/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraficas;

import Conversores.Numeros;
import Depositos.Depositos;
import Depositos.RemitosInternos;
import interfaces.Comprobable;
import interfacesPrograma.Facturar;
import java.util.ArrayList;
import java.util.Iterator;
import objetos.Articulos;
import tablas.MiTablaRemitosInternos;

/**
 *
 * @author mauro
 */
public class RecepcionDeRemitoInterno extends javax.swing.JInternalFrame {
    private RemitosInternos remitoInterno;
    private ArrayList listadoRemitos=new ArrayList();
    /**
     * Creates new form RecepcionDeRemitoInterno
     */
    public RecepcionDeRemitoInterno() {
        remitoInterno=new RemitosInternos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("RECEPCION DE REMITO INTERNO");

        MiTablaRemitosInternos tablaRemitos=new MiTablaRemitosInternos();
        Comprobable comp=new RemitosInternos();
        Facturar fact=new Articulos();
        ArrayList numeroRem=Depositos.leerRemitosInternos();
        Integer numeroRemi=(Integer)numeroRem.get(0);
        remitoInterno=(RemitosInternos)comp.leerComprobante(numeroRemi);
        Iterator itRem=remitoInterno.getArticulos().listIterator();
        jTable1.setModel(tablaRemitos);
        tablaRemitos.addColumn("CODIGO");
        tablaRemitos.addColumn("DESCRIPCION");
        tablaRemitos.addColumn("CANTIDAD");
        tablaRemitos.addColumn("ACEPTA/NO");
        Object[] fila=new Object[4];
        while(itRem.hasNext()){
            Articulos articulo=(Articulos)itRem.next();
            //articulo=(Articulos)fact.cargarPorCodigoAsignado(articulo.getNumeroId());
            fila[0]=articulo.getNumeroId();
            fila[1]=articulo.getDescripcionArticulo();
            fila[2]=articulo.getCantidad();
            fila[3]=true;
            tablaRemitos.addRow(fila);
        }
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
        );

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cantidadRow=this.jTable1.getRowCount();
        int a=0;
        for(int i=0;i < cantidadRow;i++){
            
            Articulos cant=(Articulos)remitoInterno.getArticulos().get(i);
            if((Boolean)this.jTable1.getValueAt(i, 3)){
                cant.setConfirmado(true);
                String num=String.valueOf(this.jTable1.getValueAt(i, 2));
                Double cantAct=Numeros.ConvertirStringADouble(num);
                Double dif=cantAct - cant.getCantidad();
                cant.setDiferenciaRemitida(dif);
            }else{
                cant.setConfirmado(false);
            }
            
            //System.err.println(this.jTable1.getValueAt(i, 2)+" "+cant.getCantidad());
        }
        Comprobable comp=new RemitosInternos();
        comp.modificarComprobante(remitoInterno);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
